name: Cleanup RC tags and releases

on:
  workflow_dispatch
  
jobs:
  cleanup:
    name: Cleanup RC tags and releases
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases and Tags Updated
        uses: jay2610/delete-older-releases@1.4.0
        with:
          keep_latest: 1
          delete_tags: true
          delete_tag_pattern: rc
          delete_type: prerelease
          delete_branch: rc
